# Generated by Django 3.1.3 on 2023-06-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('addr', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hall', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('addr', models.CharField(max_length=1000)),
                ('j_year', models.CharField(max_length=100)),
            ],
        ),
    ]
