# Generated by Django 3.1.3 on 2023-11-18 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='j_year',
        ),
    ]
