# Generated by Django 3.1.3 on 2023-11-19 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20231118_1351'),
    ]

    operations = [
        migrations.DeleteModel(
            name='patient',
        ),
    ]
