# Generated by Django 3.1.3 on 2023-11-19 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_delete_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='addr',
            new_name='address',
        ),
    ]
