# Generated by Django 3.1.3 on 2023-12-04 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_auto_20231204_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='phn',
            new_name='phone',
        ),
    ]
