# Generated by Django 3.1.3 on 2023-12-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_auto_20231204_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='phone',
            new_name='phn',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='address',
            field=models.CharField(max_length=1000),
        ),
    ]
