# Generated by Django 3.1.3 on 2023-12-04 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_auto_20231204_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='address',
            new_name='addr',
        ),
    ]
