# Generated by Django 3.1.3 on 2023-12-05 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_auto_20231204_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='addr',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='phn',
            new_name='phone',
        ),
    ]
