# Generated by Django 3.1.3 on 2023-12-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_auto_20231204_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=20)),
                ('healthissue', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
            ],
        ),
    ]
